### ISSUE TITLE
TMAnalysis is submitted to the cluster queuing system in benchmarking

### ISSUE THREAD

**Issue by linucks** [rigdenlab/ample#21]
When running benchmarking using the TMscore binary, the calculation of the TMscores is submitted as a job to the queuing system - ample/util/tm_util.py:comparision ~ line 200.

As on a cluster, the benchmarking job is already run under the queuing systems, and many clusters don't allow resubmission from the nodes, this causes the benchmarking to crash.

**Comment by fsimkovic** [comment]
Since the TM binary runs super fast on local machines anyway, I guess we'd just run it always 'locally' ... probably no big performance loss. I will prepare an update for this
