### ISSUE TITLE
When submitting to a cluster queueing system the ensembler_timeout is too short

### ISSUE THREAD

**Issue by linucks** [rigdenlab/ample#22]
ensembler_timeout (set in ample/include.ini) is currently 3600s, which is too short if we are using TM scoring to SPICKER.

**Comment by fsimkovic** [comment]
Have you changed this value?

**Comment by linucks** [comment]
I've just submitted a pull request that address this. @fsimkovic Is it possible to update the 1.4.4 release tag to include these changes or do we need to make a new release? I'm thinking that if these can be bundled in with 1.4.4 then it'll go in the release that Charles is currently preparing, otherwise we'll have to wait an unspecified length of time.

**Comment by fsimkovic** [comment]
Yep, could remove the tag and just associate it with a new commit hash. @hlasimpk has done this recently, could you coordinate with @linucks to do this after the PRs are accepted?

**Comment by fsimkovic** [comment]
I think this is what you're looking for @linucks https://gist.github.com/mobilemind/7883996
``` bash
# delete local tag '12345'
git tag -d 12345
# delete remote tag '12345' (eg, GitHub version too)
git push origin :refs/tags/12345
# alternative approach
git push --delete origin tagName
git tag -d tagName
```

**Comment by hlasimpk** [comment]
The `git tag -d` option was what I did last time

**Comment by fsimkovic** [comment]
Addressed in https://github.com/rigdenlab/ample/pull/50
