### ISSUE TITLE
distant homolog superposition mode now polyAla only

### ISSUE THREAD

**Issue by DanielRigden** [rigdenlab/ample#24]
I'm pretty sure using multiple distant homologs used to generate ensembles with the original side chains as well? I'm just running a job now and all the search models are polyAla. I guess this is a by-product of switching to Jens's sparse sampling mode? I think we want the default with `-homologs True` on to be to generate both poly-Ala and all side chain ensembles.

**Comment by fsimkovic** [comment]
@DanielRigden Yes almost certainly a by-product. Shall we revert back to polyAla, most reliable, and all-atom or use polyAla and all-atom only?

**Comment by DanielRigden** [comment]
I would revert back to all side chain modes
