### ISSUE TITLE
ordering of search models

### ISSUE THREAD

**Issue by DanielRigden** [rigdenlab/ample#6]
We want the 'sweet spot' ones (20-40% truncation) to run first. With 190 clusters sparsely sampled it seems that after cluster 1 sweet spot, AMPLE does others in cluster 1. We would probably prefer that it sampled across the sweet spots of all clusters rather than first covering all of cluster 1?

**Comment by fsimkovic** [comment]
**AMPLE runs search models using the following order:**

1.) Cluster 1: 20-50% → 0-20% → 50-100%
2.) Cluster 2: 20-50% → 0-20% → 50-100%
3.) Cluster 3: 20-50% → 0-20% → 50-100%
4.) ...
10.) Cluster 10: 20-50% → 0-20% → 50-100%

**We could change the order the following if that seems more sensible?!**

1.) 20-50%: c1 → c2 → c3 → c4 → ... → c10
2.) 0-20%: c1 → c2 → c3 → c4 → ... → c10
3.) 50-100%: c1 → c2 → c3 → c4 → ... → c10

---

Do you think this will be a better/faster approach? I'm not entirely convinced it will be. @linucks, what do you think?

**Comment by fsimkovic** [comment]
@DanielRigden what sort order would you like for the ``-single_model`` mode, i.e. for the CONCOORD ensemble? Does the following sound reasonable:

``truncation_level`` > ``subcluster_radius_threshold`` > ``side_chain_treatment`` > ``cluster_num``

This would basically mean all search models are first sorted by the cluster number, then side chain treatment ... and finally by the truncation level (making it the most important). Afterwards, we prioritise the sweet spot sample (20-50% ``truncation_level``) and order all ensembles as follows: 20-50% > 0-20% > 50-100%, i.e. 20-50% first.

Does that sound okay? I can submit this change immediately.
